# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablerow',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tablerow',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tablerow',
            name='rating',
        ),
        migrations.AddField(
            model_name='tablerow',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tablerow',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tablerow',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
